In [1]:
import os
from pathlib import Path
import requests
data = Path("data/")
if data.is_dir():
  print(f"{data} directory already exits...")
else:
  print(f"Creating {data}")
  data.mkdir(parents= True, exist_ok= True)

with open(data/ "names.txt", "wb") as f:
  request = requests.get("https://github.com/karpathy/makemore/raw/master/names.txt")
  print("Downloading data...")
  f.write(request.content)

Creating data


In [2]:
words = open(data/"names.txt").read().splitlines()

In [3]:
for word in words[:3]:
  chs = ['.'] + list(word) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    print(ch1, ch2, ch3)

. e m
e m m
m m a
m a .
. o l
o l i
l i v
i v i
v i a
i a .
. a v
a v a
v a .


In [4]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [53]:
btoi = {}
for i in range(27):
  for j in range(27):
    btoi[itos[i]+itos[j]] = i*27 + j

btoi

{'..': 0,
 '.a': 1,
 '.b': 2,
 '.c': 3,
 '.d': 4,
 '.e': 5,
 '.f': 6,
 '.g': 7,
 '.h': 8,
 '.i': 9,
 '.j': 10,
 '.k': 11,
 '.l': 12,
 '.m': 13,
 '.n': 14,
 '.o': 15,
 '.p': 16,
 '.q': 17,
 '.r': 18,
 '.s': 19,
 '.t': 20,
 '.u': 21,
 '.v': 22,
 '.w': 23,
 '.x': 24,
 '.y': 25,
 '.z': 26,
 'a.': 27,
 'aa': 28,
 'ab': 29,
 'ac': 30,
 'ad': 31,
 'ae': 32,
 'af': 33,
 'ag': 34,
 'ah': 35,
 'ai': 36,
 'aj': 37,
 'ak': 38,
 'al': 39,
 'am': 40,
 'an': 41,
 'ao': 42,
 'ap': 43,
 'aq': 44,
 'ar': 45,
 'as': 46,
 'at': 47,
 'au': 48,
 'av': 49,
 'aw': 50,
 'ax': 51,
 'ay': 52,
 'az': 53,
 'b.': 54,
 'ba': 55,
 'bb': 56,
 'bc': 57,
 'bd': 58,
 'be': 59,
 'bf': 60,
 'bg': 61,
 'bh': 62,
 'bi': 63,
 'bj': 64,
 'bk': 65,
 'bl': 66,
 'bm': 67,
 'bn': 68,
 'bo': 69,
 'bp': 70,
 'bq': 71,
 'br': 72,
 'bs': 73,
 'bt': 74,
 'bu': 75,
 'bv': 76,
 'bw': 77,
 'bx': 78,
 'by': 79,
 'bz': 80,
 'c.': 81,
 'ca': 82,
 'cb': 83,
 'cc': 84,
 'cd': 85,
 'ce': 86,
 'cf': 87,
 'cg': 88,
 'ch': 89,
 'ci': 90,
 'cj': 91

In [54]:
itob = {i:b for b, i in btoi.items()}

In [40]:
itob

{0: '..',
 1: '.a',
 2: '.b',
 3: '.c',
 4: '.d',
 5: '.e',
 6: '.f',
 7: '.g',
 8: '.h',
 9: '.i',
 10: '.j',
 11: '.k',
 12: '.l',
 13: '.m',
 14: '.n',
 15: '.o',
 16: '.p',
 17: '.q',
 18: '.r',
 19: '.s',
 20: '.t',
 21: '.u',
 22: '.v',
 23: '.w',
 24: '.x',
 25: '.y',
 26: '.z',
 27: 'a.',
 28: 'aa',
 29: 'ab',
 30: 'ac',
 31: 'ad',
 32: 'ae',
 33: 'af',
 34: 'ag',
 35: 'ah',
 36: 'ai',
 37: 'aj',
 38: 'ak',
 39: 'al',
 40: 'am',
 41: 'an',
 42: 'ao',
 43: 'ap',
 44: 'aq',
 45: 'ar',
 46: 'as',
 47: 'at',
 48: 'au',
 49: 'av',
 50: 'aw',
 51: 'ax',
 52: 'ay',
 53: 'az',
 54: 'b.',
 55: 'ba',
 56: 'bb',
 57: 'bc',
 58: 'bd',
 59: 'be',
 60: 'bf',
 61: 'bg',
 62: 'bh',
 63: 'bi',
 64: 'bj',
 65: 'bk',
 66: 'bl',
 67: 'bm',
 68: 'bn',
 69: 'bo',
 70: 'bp',
 71: 'bq',
 72: 'br',
 73: 'bs',
 74: 'bt',
 75: 'bu',
 76: 'bv',
 77: 'bw',
 78: 'bx',
 79: 'by',
 80: 'bz',
 81: 'c.',
 82: 'ca',
 83: 'cb',
 84: 'cc',
 85: 'cd',
 86: 'ce',
 87: 'cf',
 88: 'cg',
 89: 'ch',
 90: 'ci',
 91: 'cj'

In [5]:
import torch

In [6]:
N = torch.zeros((27, 27, 27), dtype= torch.int32)
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    N[stoi[ch1], stoi[ch2], stoi[ch3]] += 1

In [114]:
# import matplotlib.pyplot as plt
# %matplotlib inline

# # plt.figure(figsize =(32, 16))
# plt.imshow(N, cmap="Blues")
# for i in range(729):
#   for j in range(27):
#     chstr = itob[i] + itos[j]
#     plt.text(j, i, chstr, ha="center", va="bottom", color="grey")
#     plt.text(j, i, N[i, j].item(), ha="center", va="top", color="grey")
# plt.axis(False)

In [8]:
xs = []
ys = []

for word in words[:1]:
  chs = ['.'] + list(word) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    print(f"{ch1}{ch2} -> {ch3}")
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    xs.append([ix1, ix2])
    ys.append(ix3)
    # print(ch1+ch2)
    # print(ch3)

print(f"X = {xs}")
print(f"Y = {ys}")

.e -> m
em -> m
mm -> a
ma -> .
X = [[0, 5], [5, 13], [13, 13], [13, 1]]
Y = [13, 13, 1, 0]


In [9]:
xs = torch.tensor(xs)
xs

tensor([[ 0,  5],
        [ 5, 13],
        [13, 13],
        [13,  1]])

In [10]:
ys = torch.tensor(ys)
ys

tensor([13, 13,  1,  0])

In [45]:
import torch.nn.functional as F

xenc = F.one_hot(xs, num_classes=27).float()
xenc = torch.flatten(xenc, 1)
xenc.shape

torch.Size([4, 54])

In [46]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((54, 27), generator= g)
W

tensor([[ 1.5674, -0.2373, -0.0274,  ..., -0.0707,  2.4968,  2.4448],
        [-0.6701, -1.2199,  0.3031,  ...,  0.8032,  0.5411, -1.1646],
        [ 0.1476, -1.0006,  0.3801,  ..., -0.6279,  0.0770, -1.1641],
        ...,
        [ 0.5283, -0.9056, -0.0124,  ..., -0.9310, -0.0919,  0.1651],
        [-0.7125,  0.6541,  0.8071,  ..., -1.1854,  1.0008,  0.9374],
        [-0.2512, -0.8699,  0.5397,  ...,  0.0908, -0.4618, -0.8567]])

In [48]:
logits = xenc @ W
counts = logits.exp()
probs = counts/counts.sum(dim= 1, keepdims= True)
probs

tensor([[0.0237, 0.0177, 0.0107, 0.0049, 0.0223, 0.0096, 0.0111, 0.0090, 0.0071,
         0.0424, 0.0704, 0.0511, 0.0196, 0.0240, 0.2683, 0.0824, 0.0320, 0.0058,
         0.1061, 0.0203, 0.0267, 0.0060, 0.0026, 0.0565, 0.0026, 0.0264, 0.0407],
        [0.0224, 0.0482, 0.0110, 0.0675, 0.0691, 0.0033, 0.0108, 0.0058, 0.0093,
         0.0043, 0.1095, 0.0867, 0.0058, 0.0074, 0.0009, 0.0084, 0.0135, 0.0044,
         0.0651, 0.0046, 0.0327, 0.0632, 0.0720, 0.0006, 0.0040, 0.0079, 0.2616],
        [0.0226, 0.0417, 0.0201, 0.0403, 0.0219, 0.0021, 0.0284, 0.0040, 0.1099,
         0.0022, 0.0109, 0.2800, 0.0062, 0.0102, 0.0011, 0.0028, 0.0253, 0.0110,
         0.0432, 0.0012, 0.0131, 0.0155, 0.0178, 0.0045, 0.0386, 0.1600, 0.0655],
        [0.0104, 0.0781, 0.1008, 0.0187, 0.1996, 0.0441, 0.0178, 0.0055, 0.1757,
         0.0179, 0.0007, 0.0651, 0.0027, 0.0142, 0.0122, 0.0315, 0.0151, 0.0067,
         0.0196, 0.0006, 0.0230, 0.0011, 0.0198, 0.0236, 0.0645, 0.0272, 0.0040]])

In [49]:
probs.shape

torch.Size([4, 27])

In [50]:
xs.shape

torch.Size([4, 2])

In [51]:
nlls = torch.zeros(4)
for i in range(4):
  x1 = xs[i][0].item()
  x2 = xs[i][1].item()
  y = ys[i].item()
  print(f"The Actual Trigram {i+1}: {itos[x1]}{itos[x2]}{itos[y]}")
  print(f"Input to Neural Network: {x1}{x2}")
  print(f"Desired Output: {y}")
  print(f"Probabilities Assigned: {probs[i]}")
  p = probs[i, y]
  print(f"Probability Assigned to the Actual Output: {p}")
  logprob = torch.log(p)
  print(f"Loglikelihood: {logprob.item()}")
  nll = -logprob
  print(f"Negative Loglikelihood: {nll.item()}\n")
  nlls[i] = nll

print(f"Average nll: {nlls.mean()}")


The Actual Trigram 1: .em
Input to Neural Network: 05
Desired Output: 13
Probabilities Assigned: tensor([0.0237, 0.0177, 0.0107, 0.0049, 0.0223, 0.0096, 0.0111, 0.0090, 0.0071,
        0.0424, 0.0704, 0.0511, 0.0196, 0.0240, 0.2683, 0.0824, 0.0320, 0.0058,
        0.1061, 0.0203, 0.0267, 0.0060, 0.0026, 0.0565, 0.0026, 0.0264, 0.0407])
Probability Assigned to the Actual Output: 0.023988453671336174
Loglikelihood: -3.730182647705078
Negative Loglikelihood: 3.730182647705078

The Actual Trigram 2: emm
Input to Neural Network: 513
Desired Output: 13
Probabilities Assigned: tensor([0.0224, 0.0482, 0.0110, 0.0675, 0.0691, 0.0033, 0.0108, 0.0058, 0.0093,
        0.0043, 0.1095, 0.0867, 0.0058, 0.0074, 0.0009, 0.0084, 0.0135, 0.0044,
        0.0651, 0.0046, 0.0327, 0.0632, 0.0720, 0.0006, 0.0040, 0.0079, 0.2616])
Probability Assigned to the Actual Output: 0.0073710354045033455
Loglikelihood: -4.9101972579956055
Negative Loglikelihood: 4.9101972579956055

The Actual Trigram 3: mma
Input to Neu

In [52]:
loss = -probs[torch.arange(4), ys].log().mean()
loss

tensor(4.0953)

In [58]:
xs = []
ys = []

for word in words:
  chs = ['.'] + list(word) + ['.']
  for ch1, ch2, ch3 in zip(chs, chs[1:], chs[2:]):
    # print(f"{ch1}{ch2} -> {ch3}")
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    ix3 = stoi[ch3]
    xs.append([ix1, ix2])
    ys.append(ix3)

xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print(f"Number of elements: {num}")

Number of elements: 392226


In [61]:
xs.shape

torch.Size([196113, 2])

In [60]:
196113*2  #[196113, 2, 27]

392226

In [90]:
xenc = F.one_hot(xs, num_classes= 27).float()
xenc = torch.flatten(xenc, 1)
xenc.shape

torch.Size([196113, 54])

In [56]:
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((54, 27), generator=g, requires_grad= True)

In [85]:
for k in range(10):
  xenc = F.one_hot(xs, num_classes= 27).float()
  xenc = torch.flatten(xenc, 1)
  logits = xenc @ W
  #softmax
  counts = logits.exp()
  prob = counts/counts.sum(dim= 1, keepdims= True)
  loss = -prob[torch.arange(196113), ys].log().mean() + 0.01*(W**2).mean()

  print(loss.item())

  W.grad = None

  loss.backward()

  W.data += -10.0*W.grad

2.27459454536438
2.274505138397217
2.27441668510437
2.274329423904419
2.2742433547973633
2.274158239364624
2.2740743160247803
2.273991346359253
2.273909330368042
2.2738280296325684


In [88]:
for i in range(10):
  out = []
  ix1, ix2 = 0, 0

  while True:
    xenc = F.one_hot(torch.tensor([ix1, ix2]), num_classes=27).float()
    xenc = xenc.view(1, -1) # Reshape from [2, 27] to [1, 54]
    logits = xenc @ W
    counts = logits.exp()
    prob = counts / counts.sum(dim=1, keepdims=True)

    ix3 = torch.multinomial(prob, num_samples=1, replacement=True).item()

    ix1 = ix2
    ix2 = ix3

    out.append(itos[ix3])

    if ix3 == 0:
      break

  print(''.join(out))

oikhye.
avee.
ana.
olyn.
annyzalenghnnilaymde.
bemmil.
ultes.
pphi.
ashul.
allemie.
